### ISSUE TITLE
글로벌스타일 및 asset이미지 관리

### ISSUE THREAD

**Issue by kdh8615** [Develop-Space-BE/Develop-Space-FE#5]
## Description
글로벌스타일 및 asset이미지 관리

## Task
- [ ] 글로벌 스타일, style components theme
- [ ] asset 폴더에 이미지 한곳에서 관리
- [ ] 타입스크립트.config
- [ ] 스토리북 초기 셋팅

## Trouble shooting
- [ ] trouble 1 

## Etc
기타사항
